import { Property, User } from '@/types';

export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: '1',
    email: 'owner@example.com',
    fullName: 'John Doe',
    phoneNumber: '+91-9876543210',
    role: 'owner',
    verified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    password: 'password123',
  },
  {
    id: '2',
    email: 'tenant@example.com',
    fullName: 'Jane Smith',
    phoneNumber: '+91-9876543211',
    role: 'tenant',
    verified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    password: 'password123',
  },
  {
    id: '3',
    email: 'admin@example.com',
    fullName: 'Admin User',
    phoneNumber: '+91-9876543212',
    role: 'admin',
    verified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    password: 'password123',
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern 2 BHK Apartment',
    description: 'Luxurious 2 bedroom apartment in prime location with modern amenities, parking, and security.',
    type: 'residential',
    status: 'available',
    ownerId: '1',
    ownerName: 'John Doe',
    price: 4500000,
    area: 1200,
    address: '123 Main Street',
    city: 'Mumbai',
    locality: 'Bandra',
    state: 'Maharashtra',
    zipCode: '400050',
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['Parking', 'Security', 'Gym', 'Swimming Pool', 'Balcony'],
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
        alt: 'Modern apartment exterior',
        isPrimary: true,
      },
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800&h=600&fit=crop',
        alt: 'Living room',
        isPrimary: false,
      },
    ],
    isFeatured: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Commercial Space in Business District',
    description: 'Prime commercial space in the heart of the business district. Ideal for startups and established businesses.',
    type: 'commercial',
    status: 'available',
    ownerId: '1',
    ownerName: 'John Doe',
    price: 150000,
    area: 2500,
    address: '456 Business Avenue',
    city: 'Mumbai',
    locality: 'Downtown',
    state: 'Maharashtra',
    zipCode: '400001',
    amenities: ['Parking', 'Security', 'Lift'],
    images: [
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop',
        alt: 'Commercial space',
        isPrimary: true,
      },
    ],
    isFeatured: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Agricultural Land - 5 Acres',
    description: 'Well-maintained agricultural land with irrigation facilities and good road connectivity.',
    type: 'agriculture',
    status: 'available',
    ownerId: '1',
    ownerName: 'John Doe',
    price: 2500000,
    area: 20000,
    address: 'Village Road',
    city: 'Pune',
    locality: 'Outskirts',
    state: 'Maharashtra',
    zipCode: '412307',
    amenities: ['Water Supply', 'Electricity'],
    images: [
      {
        id: '4',
        url: 'https://images.unsplash.com/photo-1585421514284-efb92bd37700?w=800&h=600&fit=crop',
        alt: 'Agricultural land',
        isPrimary: true,
      },
    ],
    isFeatured: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: '3 BHK Villa with Garden',
    description: 'Spacious villa with large garden, modern kitchen, and excellent ventilation. Perfect for families.',
    type: 'residential',
    status: 'available',
    ownerId: '1',
    ownerName: 'John Doe',
    price: 8500000,
    area: 3000,
    address: '789 Garden Lane',
    city: 'Bangalore',
    locality: 'Koramangala',
    state: 'Karnataka',
    zipCode: '560034',
    bedrooms: 3,
    bathrooms: 3,
    amenities: ['Garden', 'Parking', 'Security', 'Water Supply'],
    images: [
      {
        id: '5',
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
        alt: 'Villa exterior',
        isPrimary: true,
      },
    ],
    isFeatured: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Industrial Warehouse',
    description: 'Modern industrial warehouse with high ceiling, good drainage, and ample space for storage and production.',
    type: 'industrial',
    status: 'available',
    ownerId: '1',
    ownerName: 'John Doe',
    price: 25000000,
    area: 5000,
    address: 'Industrial Area',
    city: 'Ahmedabad',
    locality: 'GIDC',
    state: 'Gujarat',
    zipCode: '382330',
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Security'],
    images: [
      {
        id: '6',
        url: 'https://images.unsplash.com/photo-1553760291-2c4f69f3f9d0?w=800&h=600&fit=crop',
        alt: 'Industrial warehouse',
        isPrimary: true,
      },
    ],
    isFeatured: false,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: '1 BHK Compact Apartment',
    description: 'Affordable 1 bedroom apartment in a well-connected locality with all essential amenities.',
    type: 'residential',
    status: 'available',
    ownerId: '1',
    ownerName: 'John Doe',
    price: 2800000,
    area: 650,
    address: '321 Park Avenue',
    city: 'Delhi',
    locality: 'Dwarka',
    state: 'Delhi',
    zipCode: '110075',
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Parking', 'Security', 'Water Supply'],
    images: [
      {
        id: '7',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
        alt: 'Apartment',
        isPrimary: true,
      },
    ],
    isFeatured: false,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CITIES = [
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Pune',
  'Ahmedabad',
  'Chennai',
  'Kolkata',
  'Hyderabad',
  'Jaipur',
  'Lucknow',
];

export const PROPERTY_TYPES = [
  'residential',
  'commercial',
  'industrial',
  'agriculture',
  'mixed'
];

export const LOCALITIES: Record<string, string[]> = {
  'Mumbai': ['Bandra', 'Downtown', 'Andheri', 'Borivali', 'Dadar'],
  'Delhi': ['Dwarka', 'Noida', 'Gurgaon', 'Indiranagar', 'Karol Bagh'],
  'Bangalore': ['Koramangala', 'Indiranagar', 'Whitefield', 'MG Road', 'Bellandur'],
  'Pune': ['Kalyani Nagar', 'Baner', 'Aundh', 'Outskirts', 'Magarpatta'],
  'Ahmedabad': ['GIDC', 'Navrangpura', 'Bodakdev', 'Vastrapur', 'Chandkheda'],
  'Chennai': ['T. Nagar', 'Adyar', 'Besant Nagar', 'Mylapore', 'Velachery'],
  'Kolkata': ['Salt Lake', 'Alipore', 'Park Circus', 'Ballygunge', 'Behala'],
  'Hyderabad': ['Hitech City', 'Jubilee Hills', 'Banjara Hills', 'Fort', 'Secunderabad'],
  'Jaipur': ['C Scheme', 'M I Road', 'Bani Park', 'Malviya Nagar', 'Raja Park'],
  'Lucknow': ['Gomti Nagar', 'Hazratganj', 'Indira Nagar', 'Alambagh', 'Aliganj'],
};
